name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common
  intl:
  path_provider: 2.1.5


  # Collection
  collection: 1.19.1

  # Convert between Enum and String
  enum_to_string: 2.2.1

  # RiverPod
  flutter_hooks: 0.21.3+1
  hooks_riverpod: 3.0.3
  riverpod_annotation: 3.0.3

  # API
  dio: 5.9.0
  pretty_dio_logger: 1.4.0
  retrofit: 4.9.1
  ua_client_hints: 1.4.1

  # Database
  shared_preferences: 2.5.4

  # Firebase
  firebase_core: 4.3.0
  firebase_messaging: 16.1.0
  firebase_crashlytics: 5.0.6
  firebase_performance_dio: 0.7.1
  firebase_remote_config: 6.1.3
  flutter_local_notifications: 19.5.0

  # Model
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  equatable: 2.0.7



  # For UI
  cupertino_icons: 1.0.8
  flutter_rating_bar: 4.0.1
  google_fonts: 6.3.3
  webview_flutter: 4.13.0

  # Screen Route
  auto_route: 11.1.0

  # Image
  cached_network_image: 3.4.1
  flutter_svg: 2.2.3

  # Scroll
  sliding_up_panel: 2.0.0+1
  carousel_slider: 5.1.1

  # Loading
  progress_indicators: 1.0.0
  loading_indicator: 3.1.1

  # For querying information about an application package.
  package_info_plus: 9.0.0

  # For launching url
  url_launcher: 6.3.2

  # For scale screen multi phones
  flutter_screenutil: 5.9.3

  # Advanced error handler and logger for dart and flutter apps
  talker_flutter: ^5.1.9
  talker_riverpod_logger: ^5.1.9
  talker_dio_logger: ^5.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  build_runner: 2.10.4

  # model gen
  freezed: 3.2.3
  json_serializable: 6.11.2

  # UI gen
  auto_route_generator: 10.4.0

  # Assets gen
  flutter_gen_runner: 5.12.0

  # API gen
  retrofit_generator: 10.2.0

  # Riverpod gen
  riverpod_generator: 3.0.3

  # For change package name quickly
  change_app_package_name: 1.5.0

dependency_overrides:
  watcher: 1.2.0
  very_good_analysis: 10.0.0

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
